version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    ports:
      - "5435:5435"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
